var  IP = 'http://txmsqudan.myhshop.top/';
var domain_test='http://h5test.myhshop.top/';//测试环境
var domain_test_server='http://txmsqudan.myhshop.top/';//接口域名
var appid="wx5937eccb3b4a99d7";
//var  IP = 'http://msqudan.myhshop.top/';
//var domain_test='http://www.myhshop.top/';//测试环境
//var domain_test_server='http://msqudan.myhshop.top/';//接口域名
//var appid = 'wx17dd8d8d9de5910e';
var path_local = 'Documents/qudan/H5/';
